# Generated by Django 3.0.3 on 2020-05-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aweme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('aweme_id', models.CharField(max_length=255, null=True)),
                ('digg_count', models.IntegerField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=999, null=True)),
                ('vid', models.CharField(max_length=255, null=True)),
                ('cover_addr', models.CharField(max_length=500, null=True)),
                ('video_addr', models.CharField(max_length=500, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('has_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'awemes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('unique_id', models.CharField(max_length=255, null=True)),
                ('aweme_count', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
                ('user_score', models.IntegerField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('source_type', models.CharField(max_length=45, null=True)),
                ('category', models.CharField(max_length=45, null=True)),
                ('keyword', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('share_url', models.CharField(max_length=255, null=True)),
                ('avatar_larger', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uid'], name='users_uid_f6e4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['category'], name='users_categor_dac109_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['keyword'], name='users_keyword_e368a8_idx'),
        ),
        migrations.AddField(
            model_name='aweme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.User'),
        ),
        migrations.AddIndex(
            model_name='aweme',
            index=models.Index(fields=['user_id'], name='awemes_user_id_edd405_idx'),
        ),
        migrations.AddIndex(
            model_name='aweme',
            index=models.Index(fields=['aweme_id'], name='awemes_aweme_i_a372b1_idx'),
        ),
        migrations.AddIndex(
            model_name='aweme',
            index=models.Index(fields=['created_at'], name='awemes_created_544a13_idx'),
        ),
    ]
